version: '3.9'

services:
  user_manage_api3:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /start
    restart: on-failure
    image: user_api
    container_name: userapp3
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
      - ./mediafiles/imgs/:/app/mediafiles/imgs/
    depends_on:
      - postgres-db3
    networks:
      - tennis-react

  nginx3:
    restart: always
    depends_on:
      - user_manage_api3
    container_name: nginx_container3
    restart: on-failure
    volumes:
      - static_volume:/app/staticfiles/
      - media_volume:/app/mediafiles/
      - ./mediafiles/imgs/:/app/mediafiles/imgs/
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - tennis-react # this network

  queue3:
    build:
      context: .
      dockerfile: ./docker/local/rabbitmq/Dockerfile
    image: user_queue_image
    container_name: user_queue3
    env_file:
      - .env
    command: 'python consumer.py'
    restart: on-failure
    depends_on:
      - postgres-db3
    networks:
      - tennis-react

  postgres-db3:
    image: postgres:12.0-alpine
    container_name: user_db3
    ports:
      - "54322:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - "./database.env"
    networks:
    - tennis-react

networks:
  tennis-react:
    name: users_network

volumes:
    postgres_data:
    static_volume:
    media_volume:
