version: '3.9'


services:
#======================================================
  user_manage_api:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /start
    image: user_manage_api
#    command: 'python manage.py runserver 0.0.0.0:8002'
    ports:
      - "8002:8002"
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - postgres-db
    networks:
      - tennis-react
#======================================================
#  queue:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: 'python -u consumer.py'
#    volumes:
#      - .:/user-management-service
#    depends_on:
#      - db
  #======================================================

  postgres-db:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
#zacki@gmail.com,123456
    env_file:
      - "./database.env"
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
    networks:
    - tennis-react

networks:
    tennis-react:
      driver: bridge

volumes:
    postgres_data:
    static_volume:
    media_volume: